#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/ghandke/mtp.git"

strains:
  - name: default
    code: *defaultRepo
    content: https://github.com/ghandke/mtpcontent.git#master
    static: *defaultRepo
